apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client
  name: client
spec:
  replicas: 36 # nodes * cores/node / threads/client
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client
    spec:
      containers:
      - command:
        - /pkg/cado/bin/cado-nfs-client.py
        - --bindir=/pkg/cado/lib/cado-nfs-3.0.0
        - --server=http://cado:37771
        image: gcr.io/always-be-factoring/cado
        name: client
        resources:
          limits:
            cpu: 2000m
          requests:
            cpu: 500m
status: {}
