apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: server-deployment
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server-deployment
    spec:
      containers:
      - command:
        - /pkg/cado/bin/cado-nfs.py
        - --server
        - --workdir=/cado/77377_148
        - server.port=37771
        - server.ssl=no
        - server.whitelist=0.0.0.0/0
        - tasks.linalg.run=false
        - "68489538134963045012753418048864718221919673024126241515190356623562112876000656094550871288326742018515941728144033256717773215207494221103043993"
        - name=77377_148
        image: gcr.io/always-be-factoring/server
        name: server
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /cado
          name: cado-volume
      volumes:
      - name: cado-volume
        gcePersistentDisk:
          pdName: cado-disk
          fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: cado
spec:
  selector:
    app: server-deployment
  ports:
    - protocol: TCP
      port: 37771
