apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: server-deployment
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server-deployment
    spec:
      containers:
      - command:
        - /pkg/cado/bin/cado-nfs.py
        - --server
        - --workdir=/cado/37773_257
        - --server-threads=8
        - --client-threads=2
        - server.port=37771
        - server.ssl=no
        - server.whitelist=0.0.0.0/0
        - "89425769958264554895944823439636244050638251300634049426350169512919910660833742278213708138883123317807680853577027067221025016904543949538314058795012731549799"
        - name=37773_257
        image: gcr.io/always-be-factoring/cado
        name: server
        resources:
          limits:
            # let the server use the whole machine for linalg etc.
            cpu: 8000m
          requests:
            cpu: 20m
        volumeMounts:
        - mountPath: /cado
          name: cado-volume
      volumes:
      - name: cado-volume
        gcePersistentDisk:
          pdName: cado-disk
          fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: cado
spec:
  selector:
    app: server-deployment
  ports:
    - protocol: TCP
      port: 37771
